prod:
  issue: '"idcf-registry"'
  loglevel: info
  debug: false
  standalone: true
  search_backend: sqlalchemy
  sqlalchemy_index_database: sqlite:////tmp/docker-registry.db

  storage: s3
  boto_bucket: _env:REGISTRY_BUCKET
  storage_path: _env:STORAGE_PATH:/registry
